-- MySQL Script generated by MySQL Workbench
-- Sat Jul 25 00:42:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema insurance
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `insurance` ;

-- -----------------------------------------------------
-- Schema insurance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `insurance` DEFAULT CHARACTER SET utf8 ;
USE `insurance` ;

-- -----------------------------------------------------
-- Table `insurance`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Customers` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(55) NOT NULL,
  `birth_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) );


-- -----------------------------------------------------
-- Table `insurance`.`Brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Brands` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_brand_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Models` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `Brands_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Models_Brands1_idx` (`Brands_id` ASC) ,
  CONSTRAINT `fk_Models_Brands1`
    FOREIGN KEY (`Brands_id`)
    REFERENCES `insurance`.`Brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Cars` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Cars` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chasis_no` INT UNSIGNED NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `Models_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Cars_Models1_idx` (`Models_id` ASC) ,
  CONSTRAINT `fk_Cars_Models1`
    FOREIGN KEY (`Models_id`)
    REFERENCES `insurance`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Countries` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Cities` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Countries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Cities_Countries1_idx` (`Countries_id` ASC) ,
  CONSTRAINT `fk_Cities_Countries1`
    FOREIGN KEY (`Countries_id`)
    REFERENCES `insurance`.`Countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Address` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `Cities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_location_UNIQUE` (`id` ASC) ,
  INDEX `fk_Address_Cities1_idx` (`Cities_id` ASC) ,
  CONSTRAINT `fk_Address_Cities1`
    FOREIGN KEY (`Cities_id`)
    REFERENCES `insurance`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Houses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Houses` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Houses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(45) NOT NULL,
  `rooms` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Houses_Address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_Houses_Address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `insurance`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Coverages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Coverages` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Coverages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `amount` FLOAT NOT NULL,
  `details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Products` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(45) NOT NULL,
  `Coverages_id` INT NOT NULL,
  `Cars_id` INT UNSIGNED NOT NULL,
  `Houses_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_seguro_UNIQUE` (`id` ASC) ,
  INDEX `fk_Products_Coverages1_idx` (`Coverages_id` ASC) ,
  INDEX `fk_Products_Cars1_idx` (`Cars_id` ASC) ,
  INDEX `fk_Products_Houses1_idx` (`Houses_id` ASC) ,
  CONSTRAINT `fk_Products_Coverages1`
    FOREIGN KEY (`Coverages_id`)
    REFERENCES `insurance`.`Coverages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Cars1`
    FOREIGN KEY (`Cars_id`)
    REFERENCES `insurance`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Houses1`
    FOREIGN KEY (`Houses_id`)
    REFERENCES `insurance`.`Houses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Company` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Offices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Offices` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Offices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Offices_Company1_idx` (`Company_id` ASC) ,
  CONSTRAINT `fk_Offices_Company1`
    FOREIGN KEY (`Company_id`)
    REFERENCES `insurance`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`payments` ;

CREATE TABLE IF NOT EXISTS `insurance`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `amount` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`employees` ;

CREATE TABLE IF NOT EXISTS `insurance`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Offices_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_employees_Offices1_idx` (`Offices_id` ASC) ,
  CONSTRAINT `fk_employees_Offices1`
    FOREIGN KEY (`Offices_id`)
    REFERENCES `insurance`.`Offices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Request` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_payment` DATE NOT NULL,
  `customers_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `total` FLOAT NOT NULL,
  `payments_id` INT NOT NULL,
  `details` VARCHAR(45) NULL,
  `employees_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Request_Customers_idx` (`customers_id` ASC) ,
  INDEX `fk_Request_Products1_idx` (`products_id` ASC) ,
  INDEX `fk_Request_payments1_idx` (`payments_id` ASC) ,
  INDEX `fk_Request_employees1_idx` (`employees_id` ASC) ,
  CONSTRAINT `fk_Request_Customers`
    FOREIGN KEY (`customers_id`)
    REFERENCES `insurance`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `insurance`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_payments1`
    FOREIGN KEY (`payments_id`)
    REFERENCES `insurance`.`payments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `insurance`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insurance`.`Phones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `insurance`.`Phones` ;

CREATE TABLE IF NOT EXISTS `insurance`.`Phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detail` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `customers_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  `Offices_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_Phones_Customers1_idx` (`customers_id` ASC) ,
  INDEX `fk_Phones_employees1_idx` (`employees_id` ASC) ,
  INDEX `fk_Phones_Offices1_idx` (`Offices_id` ASC) ,
  CONSTRAINT `fk_Phones_Customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `insurance`.`Customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Phones_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `insurance`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Phones_Offices1`
    FOREIGN KEY (`Offices_id`)
    REFERENCES `insurance`.`Offices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
